name: Update model price
description: Update a model or provider information
title: "Update model price"
body:
  - type: input
    id: model-name
    attributes:
      label: Model Name
      placeholder: GPT-3.5 Turbo
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Model price or other info.
    validations:
      required: true
  - type: input
    id: website
    attributes:
      label: Website
      placeholder: https://...
    validations:
      required: false